CREATE TABLE IF NOT EXISTS urzadzenie (
	id INTEGER NOT NULL UNIQUE,
	nazwa VARCHAR(255),
	przetargid INTEGER,
	numerseryjny VARCHAR(255),
	stan VARCHAR(255),
	modelid INTEGER,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS pracownik (
	id INTEGER NOT NULL UNIQUE,
	imie VARCHAR(255),
	nazwisko VARCHAR(255),
	dzialid INTEGER,
	kartaid INTEGER,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS przetarg (
	id INTEGER NOT NULL UNIQUE,
	numerumowy VARCHAR(255),
	datarozpoczecia TIMESTAMP,
	datazakonczenia TIMESTAMP,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS dzial (
	id INTEGER NOT NULL UNIQUE,
	nazwa VARCHAR(255),
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS lokalizacja (
	id INTEGER NOT NULL UNIQUE,
	pokoj INTEGER,
	budynekid INTEGER,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS budynek (
	id INTEGER NOT NULL UNIQUE,
	adres VARCHAR(255),
	oznaczenie VARCHAR(255),
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS karta (
	id INTEGER NOT NULL UNIQUE,
	numer VARCHAR(255),
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS producent (
	id INTEGER NOT NULL UNIQUE,
	nazwa VARCHAR(255),
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS model (
	id INTEGER NOT NULL UNIQUE,
	nazwa VARCHAR(255),
	producentid INTEGER,
	PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS historiaoperacji (
	id INTEGER NOT NULL UNIQUE,
	urzadzenieid INTEGER,
	pracownikid INTEGER,
	lokalizacjaid INTEGER,
	data_zdarzenia TIMESTAMP,
	log VARCHAR(255),
	PRIMARY KEY(id)
);


ALTER TABLE urzadzenie
ADD FOREIGN KEY(przetargid) REFERENCES przetarg(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE urzadzenie
ADD FOREIGN KEY(modelid) REFERENCES model(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE pracownik
ADD FOREIGN KEY(dzialid) REFERENCES dzial(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE pracownik
ADD FOREIGN KEY(kartaid) REFERENCES karta(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE lokalizacja
ADD FOREIGN KEY(budynekid) REFERENCES budynek(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE model
ADD FOREIGN KEY(producentid) REFERENCES producent(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE historiaoperacji
ADD FOREIGN KEY(urzadzenieid) REFERENCES urzadzenie(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE historiaoperacji
ADD FOREIGN KEY(pracownikid) REFERENCES pracownik(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE historiaoperacji
ADD FOREIGN KEY(lokalizacjaid) REFERENCES lokalizacja(id)
ON UPDATE NO ACTION ON DELETE NO ACTION;